name: Bug Report
description: If you encounter a bug whilst using the website. Please use this template to help improve the website.
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: markdown
    id: message
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read and agree to follow the [code of conduct](.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have read and agree to follow the [contributing guide](.github/CONTRIBUTING.md).
          required: true
        - label: I have searched the [issue tracker](https://github.com/Paperback-iOS/website/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device have you encountered the bug with?
      multiple: true
      options:
        - All device types
        - Computers
        - Phones
    validations:
      required: true
  - type: input
    id: browser-type
    attributes:
      label: Browser Type
      description: What browser have you encountered the bug with?
      placeholder: 'e.g. Windows 11 Version 22H2, macOS Ventura 13.5 or iOS 16.6'
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug that you encountered. Tell us what you expected to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: bug-replication
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug, tell us how you did it so we can reproduce it ourselves.
      placeholder: 1. ...
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the bug you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Images, links, logs, ...
    validations:
      required: false
