name: Question
description: If you have a question regarding the website.
title: '[QUESTION] '
labels: ['question']
assignees: []
body:
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read and agree to follow the [code of conduct](.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have read and agree to follow the [contributing guide](.github/CONTRIBUTING.md).
          required: true
        - label: I have searched the [issue tracker](https://github.com/Paperback-iOS/website/issues) for a question that matches the one I want to file, without success.
          required: true
  - type: textarea
    id: question-description
    attributes:
      label: Describe Your Question
      description: A clear and concise description of your question.
      placeholder: Ask away!
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the question which you are asking!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Images, links, ...
    validations:
      required: false
